### ISSUE TITLE
Combine fa.gz and fai inputs to the fasta-index input

### ISSUE THREAD

**Issue by Addy81** [eastgenomics/eggd_vcfeval_hap.py#25]
At the moment the app expects compressed fasta file (fa.gz) and a fasta index of the uncompressed fasta file which could cause issues downstream if wrong files are selected. 

Propose to combine those two inputs to one and use the fasta-index tar which contains both.

**Comment by Emma-MacK** [comment]
Issue resolved with PR #26  
The app now takes a fasta-index tar as one input rather than a fasta and index separately
